### ISSUE TITLE
源码运行错误

### ISSUE THREAD

**Issue by bdgis** [littleredhat1997/Ethereum#11]
Failed to execute goal org.web3j:web3j-maven-plugin:4.5.11:generate-sources (default-cli) on project demo: Could not compile solidity files
unrecognised option '--allow-paths'

您好，我这边下载源码，然后点击web3j:generate-sources后出现上述错误，请问有遇到过吗？谢谢
![image](https://user-images.githubusercontent.com/40384973/103094589-fbb52e00-4638-11eb-894a-103cea7127f3.png

**Comment by zhangbincheng1997** [comment]
没遇到过，看起来像是合约路径错了？
