### ISSUE TITLE
这个命令是干嘛的？

### ISSUE THREAD

**Issue by huanleyuan** [littleredhat1997/Ethereum#2]
make geth后
ln -s build/bin/geth /usr/bin/geth # 软链接
这个命令是干嘛的？ln: failed to create symbolic link '/usr/bin/geth': File exists

**Comment by littleredhat1997** [comment]
软链接。/usr/bin是环境变量之一，将build后的geth软链接到/usr/bin，方便通过命令行输入 geth 启动。
另外通过ppa安装更方便。
