### ISSUE TITLE
we couldn't estimate the gas

### ISSUE THREAD

**Issue by huanleyuan** [littleredhat1997/Ethereum#3]
after click deploy,error tip like this:"it seems this transaction will fail,we couldn't estimate the gas",it may consume all the gas you provide.(钱包挖矿所得4665 ETHER)
钱包界面里没有gas设置，只有genesis.json里有 "gasLimit"   : "0x2fefd8",.
想看下你的genesis.json

**Comment by huanleyuan** [comment]
Gas used   153,000     
helloworld合约这个值咋这么大？钱包里有一万元不够，这个值哪里可以改小？

**Comment by littleredhat1997** [comment]
@huanleyuan 因为 gas 并不是以太币单位。以太坊中花费 = gasPrice * gasUsed，单位为 wei。
1 ether = 10 ^ 18 wei
