### ISSUE TITLE
contract列表没有显示helloworld合约

### ISSUE THREAD

**Issue by huanleyuan** [littleredhat1997/Ethereum#4]
部署的合约只在wallet下显示，0 of 12 confirmation，contract列表没有显示helloworld合约

**Comment by littleredhat1997** [comment]
不可能吧，Wallet显示的是账号吧？下方列表显示的是处理中的事务。如果你部署成功了但是在Contract没看到，那可能是因为你没有挖矿。。。只有挖矿才能成功将合约写入区块哦。

**Comment by huanleyuan** [comment]
然，这台电脑挖起来就很快有确认了，（但是挖矿区块高度在变money数字不变）
不管怎样，heloworld跑起来了，谢谢小兄弟，年纪轻轻就这么厉害了

**Comment by littleredhat1997** [comment]
@huanleyuan 以太坊学习算简单的了。。。超级账本fabric 环境比这复杂N倍，更别说它的SDK各种文档不齐全。。。

**Comment by luoxianjiao** [comment]
你好，运行heloworld的时候 经常出现 Error processing transaction request: replacement transaction underpriced的错误，GAS_PRICE 和 GAS_LIMIT 你是设置的是多少呢？

**Comment by luoxianjiao** [comment]
@littleredhat1997 你好，运行heloworld的时候 经常出现 Error processing transaction request: replacement transaction underpriced的错误，GAS_PRICE 和 GAS_LIMIT 你是设置的是多少呢？

**Comment by littleredhat1997** [comment]
@luoxianjiao 被qq当成垃圾邮件了，没看到抱歉。
就是工程配置文件的默认值，这个默认值应该很高了。还有你说的“经常出现”，有时候是正常的吗？
