### ISSUE TITLE
Ethereum

### ISSUE THREAD

**Issue by huanleyuan** [littleredhat1997/Ethereum#5]
这个java版的helloworld的三种方式都ok,但既然是跑在以太坊上的，那怎么和本地的以太坊EthereumJ java版源码发生联系呢？我想在EthereumJ里打下log看看流程，比如挖矿和交易确认的代码是怎么确认的，两个项目是要在ide里建立依赖关系吗？

**Comment by littleredhat1997** [comment]
@huanleyuan 我没有用过EthereumJ，我用的是基于Go语言的客户端，不太清楚怎么一回事，抱歉。
