### ISSUE TITLE
前辈你好！请教一个关于同步以太坊钱包数据格式问题

### ISSUE THREAD

**Issue by IianWang** [littleredhat1997/Ethereum#9]
起因是我同步了以太坊钱包数据，生成了很多的ldb文件与cdat文件，我想读取.ldb与.cdat里面的合约数据，不过不知道怎样打开。下载下来的文件夹是这样的
![image](https://user-images.githubusercontent.com/40428181/64663003-ea183900-d47c-11e9-86ad-197786ef879e.png)
看到您在文章中有例举·
![image](https://user-images.githubusercontent.com/40428181/64663077-32375b80-d47d-11e9-97f2-b207761ba817.png)
这与我同步下来的几个文件很像，请问
000001.log
CURRENT

**Comment by IianWang** [comment]
抱歉，没写完就发出去了。。。下面我补上剩下的的问题
LOCK
LOG
MANIFEST-000000
您文中的这些文件分别代表什么呢，在读取ldb文件时它们起到什么作用，还是没作用？

**Comment by littleredhat1997** [comment]
以太坊底层数据库为LevelDB，可以参考这篇文章：
https://uzshare.com/view/2025

![image](https://user-images.githubusercontent.com/18366691/64904404-3ae99500-d6fc-11e9-8914-e109eb55d041.png)

具体怎么读取需要研究底层区块设计的数据结构......

**Comment by IianWang** [comment]
> 以太坊底层数据库为LevelDB，可以参考这篇文章：
> https://uzshare.com/view/2025
> 
> ![image](https://user-images.githubusercontent.com/18366691/64904404-3ae99500-d6fc-11e9-8914-e109eb55d041.png)
> 
> 具体怎么读取需要研究底层区块设计的数据结构......

学到了，非常的感谢
